### ISSUE TITLE
Some addresses fail to load

### ISSUE THREAD

**Issue by afragapane** [neotracker/neotracker#121]
### Description
Certain addresses seem to fail to load.  Both their wallet & address pages.

### Steps to Reproduce
https://neotracker.io/address/ATgiAKdLvxiiDnwiom3TWXHLtfXfH4KDJb

**Expected behavior:** [What you expect to happen]
Displays address page

**Actual behavior:** [What actually happens]
Loads forever

**Reproduces how often:** [What percentage of the time does it reproduce?]
Seems like 100% for certain addresses?  Haven't tracked closely enough to say for sure though.

**Comment by spencercorwin** [comment]
Duplicate of #131, so I'm going to close this one. And add notes to the other one.
