### ISSUE TITLE
Add uptime monitoring

### ISSUE THREAD

**Issue by spencercorwin** [neotracker/neotracker#147]
### Description

We need to be notified somehow when the website goes down, nodes go down, the scraper goes down, or the DB goes down, etc.

Potential solutions:
- [Pingdom](https://www.pingdom.com/product/uptime-monitoring/)
- Grafana
- Custom Slack alert service
- Other Kubernetes add-on?

**Comment by danwbyrne** [comment]
https://my.pingdom.com/app/reports/uptime#check=5975252

probably good to close this issue if we just want to use pingdom now. It looks like it has what we need

**Comment by spencercorwin** [comment]
The only concern I have is cost. Right now we're operating on a 14-day free-trial.

<img width="848" alt="Screen Shot 2020-04-20 at 12 18 46 PM" src="https://user-images.githubusercontent.com/29364457/79790756-180e0780-8301-11ea-9a36-ed43225546ee.png">

**Comment by danwbyrne** [comment]
Okay lets talk about this at standup tomorrow.

Do we know how much some of the other options cost? We still get grafana alerts so I assume we still have an account there as well.

**Comment by spencercorwin** [comment]
We went with the Pingdom starter plan for 1 year.
