### ISSUE TITLE
Test C# Node with NEO Tracker

### ISSUE THREAD

**Issue by afragapane** [neotracker/neotracker#174]
### Description
These are the steps I have been taking to test the C# node & `NEODataProvider` on NEO Tracker.
  
1) Run a fully-synced mainnet node using the 2.x neo-cli (https://github.com/neo-project/neo-node).   I used the precompiled 2.10.3 binary found in the `releases`.  Make sure the following plugins are installed (https://github.com/neo-project/neo-modules/tree/master-2.x):
- `ImportBlocks`
- `SimplePolicy`
- `RpcSystemAssetTracker`: Note that this plugin has its own storage and also needs time to sync.  e.g. if it is installed after the chain has been synced then it will take some time for this plugin to catch up.  

2) Start postgres locally using the instructions on the neotracker README

3) Start the scraper using `yarn develop` with the neo-cli node & local postgres.

4) If/when the scraper fails, look at the reason for the shutdown and debug from there.  
- My first step is usually to query the block which failed using a script with a `NEODataProvider` or `JSONRPCClient` (find the block index before failure by starting the web component without the scrape).  By printing the result to the console you should be able to see if there is any missing or unexpected data in the block which is causing the issue.
Something like:   
```
const rpcURL = 'http://localhost:10332/rpc';
const jsonClient = new JSONRPCClient(new JSONRPCHTTPProvider(rpcURL));
const provider = new NEODataProvider({
  network: 'main',
  rpcURL,
});

provider.getBlock(1234567).then((block) => console.log(block))
```

### Relevant PR
This PR contains more information about specific issues discovered so far: https://github.com/neotracker/neotracker/pull/173

**Comment by spencercorwin** [comment]
See https://github.com/neo-one-suite/neo-one/issues/2055
