### ISSUE TITLE
Readme instructions don't work

### ISSUE THREAD

**Issue by adamstallard** [neotracker/neotracker#56]
### Description

Attempting to run the web service using the instructions in [README.md](https://github.com/neotracker/neotracker/blob/master/README.md) doesn't work.

### Steps to Reproduce

1. `` yarn develop:scrape``

**Expected behavior:**

(start the scraper which populates postgres with blockchain data)

**Actual behavior:**

```
yarn run v1.9.4
error Command "develop:scrape" not found.
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

**Comment by danwbyrne** [comment]
should be fixed.
