### ISSUE TITLE
nep-5 transfer display when transfer failed

### ISSUE THREAD

**Issue by KickSeason** [neotracker/neotracker#57]
### Description
when a nep-5 transfer transaction is confirmed, whether the asset is transferred or not if the contract execution state is "Halt", neo-tracker will display the asset from one to another.

### Steps to Reproduce

1. [First Step] deploy a nep-5 contract
2. [Second Step] relay a nep-5 transfer transaction which from_address has no enouth asset
3. [and so on...] despite the contract execution state is "Halt", but neotracker will show the transfer detail and influence the balance of to_address on neotracker

**Expected behavior:** [What you expect to happen]
when transfer return false, dont show detail and dont add asset to to_address.
**Actual behavior:** [What actually happens]
In the page of transaction detail, it shows the asset transferred from one to another.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Additional Information
you can search this tx and compare neotracker showing and the applicationlog of neo-cli or other neo block chain browser.
txid: da79bd42c88d20867dd0edf829283da92d01a19badc5cbb7cd67aa00adc06af3

btw: I browse your code in function **calculateTransactionData** of **getTransactionDataForClient.ts**.
I think neotracker uses it to analyse transactions from block and then inserts the details into Db, am I right?
if it is a invocation-transaction and invocaton.result.stat is 'HALT',  neotracker will translate script into inputs and outputs using parameters?
In one scenario, despite the contract executing smoothly but it return false, the state is "HALT" too.
I'm afraid better to use notification of a transfer handled successfully.

**Comment by dicarlo2** [comment]
Thanks for the detailed report, we'll take a look!

**Comment by KickSeason** [comment]
hi, i think it is something about vm.
please check the state of txid:7675730ba70b6e818c6d5b904d278356d08a562ec529d8d39531f3ef6e2e5492.
I use getapplicaitonlog api of neo-cli, and get Halt and notifications.
but Falt and error message from neotracker.io/rpc.
I hope this can help.

**Comment by spencercorwin** [comment]
This should be fixed with our recent node upgrade. And if not then it will be soon with our new C# node integration.
