### ISSUE TITLE
transfer issue

### ISSUE THREAD

**Issue by Wherearemycoins** [neotracker/neotracker#59]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Wherearemycoins** [comment]
Can't see my original query so re-stating it here.
Transferred ontology to my tracker wallet last week from exchange but can't see it in the wallet. Exchange sent me this confirmation 

  | Sean (CoinSpot)                                                                                      May 7, 21:18 AEST                                                Hi,I can see this transaction is successful on the blockchain here:https://explorer.ont.io/transaction/ce8a5c2185677574bca4b105f3a5c3f0288d52e5796bd6a79cff2b91b1fcb8f1If  you are missing your coins then please get in touch with your receiving  wallets support team regarding this and show them the above link.Kind Regards,Sean
-- | --


What should I do next?
Thanks

**Comment by merl111** [comment]
ONT on exchanges is not a NEP5 token anymore. Ontology launched it's own blockchain in July 2018. Neotracker is a NEO only wallet, so please use an Ontology wallet and login with the same details you used to login to Neotracker.
