### ISSUE TITLE
Fix CoinTable height

### ISSUE THREAD

**Issue by dicarlo2** [neotracker/neotracker#9]
Search for usages of [COIN_TABLE_ROW_HEIGHT](https://github.com/neotracker/neotracker/blob/master/packages/neotracker-shared-web/src/components/explorer/address/lib/CoinTable.js#L40) to find where we're not calculating it correctly. Oddly enough, it seems like the height is correct when there's an even number of coins, but not when there's an odd number.

**Comment by afragapane** [comment]
There seems to be an issue with the query result used to calculate the number of coins.  addresses.edges.node.coins.edges is the wrong length for all odd number coins and some even number coins.  See this address with 4 coins for example which displays 2 on the Address Search page:
https://neotracker.io/address/AGxrCsGjUeuaNjPmRbcLprjg8ybRzaYGU1
